### ISSUE TITLE
consider using setup_cache

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#12]
I see us using our hand-written helpers to cache the generated dir in `add.py`. Seems like there is a better solution

> The setup method is run multiple times, for each benchmark and for each repeat. If the setup is especially expensive, the setup_cache method may be used instead, which only performs the setup calculation once and then caches the result to disk. It is run only once also for repeated benchmarks and profiling, unlike setup.

**Comment by pared** [comment]
I am afraid that `setup_cache` might not be useful for us.
> which only performs the setup calculation once and then caches the result to disk

What asv can do is to cache in-memory objects and write them to `cache.pickle` file under temporary benchmark dir. When `setup_cache` is defined, `asv` [tries to load pickled object](https://github.com/airspeed-velocity/asv/blob/9173bcaa997dd3b9bebdfd762950443a1d989706/asv/benchmark.py#L1027). I believe that this approach does not make too much sense for us, since we depend on the repository and its state.

**Comment by efiop** [comment]
@pared Makes sense.

**Comment by pared** [comment]
Closing for now
