### ISSUE TITLE
add bigger data sizes

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#306]
E.g. 1M files dataset, and 10M (maybe more as well?) dataset would be great to have.

**Comment by pared** [comment]
It seems to me that we could try obtaining ImageNet for this use case. Its de-facto a standard dataset and can actually be used to fulfill both needs. 
The whole dataset contains around 14M images, and the most used subset is around 1.3 M samples.
The license can be found here: https://image-net.org/download.php
Seems to me that benchmarking would fall into the research category.
I haven't yet requested access due to the last point of the license.

**Comment by efiop** [comment]
It is probably better to just use https://pypi.org/project/Faker/ to generate the biggest dataset and then have small/tiny/etc options based on it, as we do now.

**Comment by daavoo** [comment]
https://storage.googleapis.com/openimages/web/download.html ?

I'm missing some context but, why not just generate X images with random pixels. Like:

```python
import numpy
from PIL import Image

NUM_IMAGES = 1e6
for i in range(NUM_IMAGES):
    array = numpy.random.rand(100,100,3) * 255
    img = Image.fromarray(array.astype('uint8')).convert('RGBA')
    im.save(f"dataset/{i}.png"))
```

**Comment by daavoo** [comment]
It would be also nice to have a dataset with big individual fiels
