### ISSUE TITLE
ci: pytest freezing for hours from time-to-time

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#319]
Looks like this has been happening for awhile, but would work once in a few days. E.g. https://github.com/iterative/dvc-bench/runs/4999679781?check_suite_focus=true

2.9.x is specifically the one that seems to be freezing, might be related to other reports of degraded performance.

**Comment by karajan1001** [comment]
Still fails every day ? 
![image](https://user-images.githubusercontent.com/6745454/160599608-92a23b58-458c-4dbd-881a-387ebdfb4b90.png)

**Comment by dtrifiro** [comment]
One of the first builds including the fix was [this one](https://github.com/iterative/dvc-bench/actions/runs/2055589372), seems it fails because of the `lint` task: see https://github.com/iterative/dvc-bench/runs/5729419610?check_suite_focus=true#step:5:39, which is related to [this](https://github.com/pallets/click/issues/2232) click issue

**Comment by dtrifiro** [comment]
Closing as it seems solved
